version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-1.1.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: app:localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "javascript:1:1,java:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  app:
    build: ./git-repos-producer
    ports:
      - "3009:3009"
    environment:
      NODE_ENV: production
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_CLIENT_ID: my-app
    volumes:
      - ./git-repos-producer:/app